language: scala
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot/
matrix:
  include:
    - os: linux
      jdk: openjdk-ea
    - os: linux
      jdk: openjdk13
    - os: linux
      jdk: openjdk11
    - os: osx
      jdk: openjdk13
    - os: osx
      jdk: openjdk11
  allow_failures:
    - jdk: openjdk-ea
scala:
  - 2.13.1
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport
  - find $HOME/.sbt -name "*.lock" | xargs rm
after_success:
  - bash <(curl -s https://codecov.io/bash)
